"""Remove seller table from db model

Revision ID: 18c4df39dc04
Revises: 2141bf2e9022
Create Date: 2024-04-14 13:38:24.454490

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '18c4df39dc04'
down_revision = '2141bf2e9022'
branch_labels = None
depends_on = None

# ### commands auto generated by Alembic - please adjust! ###

def upgrade():
    op.drop_table('seller')
    
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))

    listing_table = sa.Table('listing', sa.MetaData())
    fkeys = [fk.name for fk in listing_table.foreign_keys]
    if 'listing_seller_id_fkey' in fkeys:
        op.drop_constraint('listing_seller_id_fkey', 'listing', type_='foreignkey')

    op.create_foreign_key(None, 'listing', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_column('seller_id')

# ### end Alembic commands ###

def downgrade():

    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_id', sa.INTEGER(), autoincrement=False, nullable=False))

    op.create_foreign_key('listing_seller_id_fkey', 'listing', 'seller', ['seller_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_column('user_id')

# ### end Alembic commands ###