"""Change relationship of SavedItem within User table

Revision ID: 5a9b344a5cac
Revises: 18c4df39dc04
Create Date: 2024-04-16 12:59:44.404657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a9b344a5cac'
down_revision = '18c4df39dc04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_saved_item_id_fkey', type_='foreignkey')
        batch_op.drop_column('saved_item_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saved_item_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('user_saved_item_id_fkey', 'saved_item', ['saved_item_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
