"""added initial password functionality

Revision ID: 785ba1d0a241
Revises: 9b31e216b2c7
Create Date: 2024-04-13 15:43:17.460806

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '785ba1d0a241'
down_revision = '9b31e216b2c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=25),
               nullable=False)
        batch_op.alter_column('species',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('tree_type',
               existing_type=sa.VARCHAR(length=25),
               nullable=False)
        batch_op.alter_column('indoor_outdoor',
               existing_type=sa.VARCHAR(length=7),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('height',
               existing_type=sa.NUMERIC(precision=5, scale=0),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('care_tips',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('image',
               existing_type=postgresql.BYTEA(),
               nullable=False)
        batch_op.alter_column('date_added',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('seller_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('saved_item', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'listing', ['listing_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))
        batch_op.alter_column('saved_item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('password_hashed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hashed', sa.VARCHAR(length=25), autoincrement=False, nullable=False))
        batch_op.alter_column('saved_item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('saved_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.alter_column('seller_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('date_added',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('image',
               existing_type=postgresql.BYTEA(),
               nullable=True)
        batch_op.alter_column('care_tips',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('height',
               existing_type=sa.NUMERIC(precision=5, scale=0),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('indoor_outdoor',
               existing_type=sa.VARCHAR(length=7),
               nullable=True)
        batch_op.alter_column('tree_type',
               existing_type=sa.VARCHAR(length=25),
               nullable=True)
        batch_op.alter_column('species',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=25),
               nullable=True)

    # ### end Alembic commands ###
