"""Initial migration

Revision ID: 9b31e216b2c7
Revises: 
Create Date: 2024-04-13 08:53:20.661855

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9b31e216b2c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_item', schema=None) as batch_op:
        batch_op.drop_constraint('saved_item_tree_id_fkey', type_='foreignkey')

    op.drop_table('tree')

    with op.batch_alter_table('saved_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listing_id', sa.Integer(), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('tree_id')

    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('saved_item_id',
               existing_type=sa.INTEGER(),
               nullable=False)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('saved_item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('saved_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tree_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('saved_item_tree_id_fkey', 'tree', ['tree_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('listing_id')

    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.alter_column('seller_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('date_added',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('image',
               existing_type=postgresql.BYTEA(),
               nullable=True)
        batch_op.alter_column('care_tips',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('height',
               existing_type=sa.NUMERIC(precision=5, scale=0),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('indoor_outdoor',
               existing_type=sa.VARCHAR(length=7),
               nullable=True)
        batch_op.alter_column('tree_type',
               existing_type=sa.VARCHAR(length=25),
               nullable=True)
        batch_op.alter_column('species',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=25),
               nullable=True)

    op.create_table('tree',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('species', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('tree_type', sa.VARCHAR(length=25), autoincrement=False, nullable=True),
    sa.Column('indoor_outdoor', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('height', sa.NUMERIC(precision=5, scale=0), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('care_tips', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('image', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('date_added', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('seller_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['seller.id'], name='tree_seller_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='tree_pkey')
    )
    # ### end Alembic commands ###
